#!/usr/bin/python3
def find_monthDays():
    """
    Function to find the number of days in a given month

    Prompts the user to enter a month name and then prints the number of days in that month.

    Args:
        None

    Returns:
        None
    """
    m = input("Enter Month name: ")
    _31_days = "January March May July August October December"
    _30_days = "April June September November"
    _28_and_29_days = "February"

    if m.lower() == _28_and_29_days.lower():
        print(f"{m} has 28 or 29 Days")
    
    for i in range(7):
        if m.lower() == _31_days.lower().split()[i]:
            print(f"{m} has 31 Days")
        else:
            pass
    
    for i in range(4):
        if m.lower() == _30_days.lower().split()[i]:
            print(f"{m} has 30 Days")
        else:
            pass

find_monthDays()
