#!/usr/bin/python3
def convert_to_DogYear():
    """
    Convert human years to dog years

    Prompts the user to enter the number of human years and converts it to
    dog years using the following rules:
    - The first two human years are equivalent to 10.5 dog years each.
    - Each subsequent human year is equivalent to 4 dog years.

    Args:
        None

    Returns:
        None
    """
    y = int(input("Enter the number of human years: "))  # Prompt user for input
    if y < 0:
        print("Error, enter a valid number of years!")  # Handle negative input
    else:
        dog_year = 0
        for i in range(y):
            if i < 2:
                dog_year += 10.5  # Add 10.5 dog years for each of the first two human years
            elif i >= 2:
                dog_year += 4  # Add 4 dog years for each human year after the first two
            else:
                pass
        print(f"{y} Human Years = {dog_year:.1f} Dog Years")  # Output the result

convert_to_DogYear()
