#!/usr/bin/python3
def find_ZodiacSign():
    """
    Find Zodiac Sign function

    Prompts the user to enter their birthday month and day,
    and then prints the corresponding Zodiac sign.

    Returns:
        None
    """
    zodiac_signs = {
        "January": (20, "Capricorn", "Aquarius"),
        "February": (19, "Aquarius", "Pisces"),
        "March": (21, "Pisces", "Aries"),
        "April": (20, "Aries", "Taurus"),
        "May": (21, "Taurus", "Gemini"),
        "June": (21, "Gemini", "Cancer"),
        "July": (23, "Cancer", "Leo"),
        "August": (23, "Leo", "Virgo"),
        "September": (23, "Virgo", "Libra"),
        "October": (23, "Libra", "Scorpio"),
        "November": (22, "Scorpio", "Sagittarius"),
        "December": (22, "Sagittarius", "Capricorn")
    }

    m = input("Enter your birthday month: ")
    d = int(input("Enter birthday day: "))

    if m in zodiac_signs:
        cutoff, sign1, sign2 = zodiac_signs[m]
        if d < cutoff:
            print(f"Your Zodiac sign is: {sign1}.")
        else:
            print(f"Your Zodiac sign is: {sign2}.")
    else:
        print("Invalid month!")

find_ZodiacSign()
