#!/usr/bin/python3
def convert_UnitsPressure():
    """
    My pressure conversion function

    Prompts the user to enter a pressure value in kilopascals and converts it to 
    pounds per square inch (psi), millimeters of mercury (mmHg), and atmospheres (atm).
    
    Args:
        None

    Returns:
        None
    """
    # Prompt user to input the pressure in kilopascals
    kpa = int(input("Enter the pressure in Kilopascal: "))

    # Convert kilopascals to pounds per square inch
    psi = kpa / 6.895

    # Convert kilopascals to millimeters of mercury
    mmhg = kpa * 7.50062

    # Convert kilopascals to atmospheres
    atm = kpa / 101.3

    # Print the conversion results
    print(f"{kpa} kilopascals \n\
          ==> {psi:.3f} pounds per square inch,\n\
          ==> {mmhg:.3f} millimeters of mercury \n\
          ==> {atm:.3f} atmospheres")

# Call the function to execute the pressure conversion
convert_UnitsPressure()
