#!/usr/bin/python3
def compound_interest():
    """Calculates compound interest over 3 years

    Prompts the user to enter the initial balance and computes the balance 
    at the end of each year with an interest rate of 4%.

    Args:
        None

    Returns:
        None
    """
    initial_amount = float(input("Enter your initial balance $: "))
    interest_rate = 0.04
    current_balance = initial_amount
    for i in range(1, 4):
        current_balance += current_balance * interest_rate
        if i == 1:
            print(f"After {i} year, the balance is: ${current_balance:.2f}")
        elif i > 1:
            print(f"After {i} years, the balance is: ${current_balance:.2f}")
        else:
            pass

compound_interest()
